apiVersion: v1
kind: Service
metadata:
  name: simple-flask-service
spec:
  type: NodePort
  selector:
    app: simple-flask-app
  ports:
    - protocol: TCP
      port: 5070
      targetPort: 5070
      nodePort: 30009   
